### ISSUE TITLE
To Do: Nested Recycler View for Interest Page

### ISSUE THREAD

**Issue by henrylao** [SquadHouseDev/SquadHouse#37]
![image](https://user-images.githubusercontent.com/22669913/113893834-3d975980-977c-11eb-93d7-eb2b281fd012.png)

Resources:
- https://oozou.com/blog/implementing-a-nested-recyclerview-in-android-with-concatadapter-57
- https://stackoverflow.com/questions/30079438/how-do-i-layout-nested-recyclerviews-while-remaining-performant
- https://medium.com/android-news/easily-adding-nested-recycler-view-in-android-a7e9f7f04047

**Comment by henrylao** [comment]
A user is able to configure a set of personal Interests. 
Interests are to be used as topic tags (stretch feature) when querying for rooms to populate the home feed. 
Interests are also used in the explore page where a user is able to search for active rooms based upon a selected interest archetype.

- [x] User is able to configure a set of personal interests
- [ ] User is able to explore active rooms based on Interest
- [ ] User's home feed is populated based upon Interests
- [ ] Clubs are able to create their own club interest

**Comment by henrylao** [comment]
2021-04-10 09:19:29.379 4778-4778/com.pepetech.squadhouse E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pepetech.squadhouse, PID: 4778
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
        at com.pepetech.squadhouse.activities.Settings.adapters.OuterInterestAdapter.getItemCount(OuterInterestAdapter.java:57)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4044)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3534)
        at android.view.View.measure(View.java:25466)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:490)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3397)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2228)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2486)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
